import ArrowDown from "./arrow-down.svg";
import Event from "./event.svg";
import Integration from "./integration.svg";
import Setting from './setting.svg';
import Log from './log.svg';
import Metric from './metric.svg';
import InApp from './inapp.svg';
import Mail from './mail.svg';
import Other from './other.svg';
export { ArrowDown, Event, Integration, Setting, Log, Metric, InApp, Mail, Other };
